#!/usr/bin/env python3
"""Generate F1TENTH map variants with random static square obstacles."""
from __future__ import annotations

import argparse
import csv
import json
import math
import random
from pathlib import Path


def _read_pgm(path: Path) -> tuple[bytearray, int, int, int]:
    with path.open("rb") as f:
        magic = f.readline().strip()
        if magic != b"P5":
            raise ValueError(f"Only binary P5 PGM files are supported: {path}")

        tokens: list[bytes] = []
        while len(tokens) < 3:
            line = f.readline()
            if not line:
                raise ValueError(f"Malformed PGM header: {path}")
            line = line.split(b"#", 1)[0].strip()
            if line:
                tokens.extend(line.split())

        width, height, max_value = (int(token) for token in tokens[:3])
        data = bytearray(f.read(width * height))
        if len(data) != width * height:
            raise ValueError(f"PGM payload size does not match header: {path}")
        return data, width, height, max_value


def _write_pgm(path: Path, image: bytearray, width: int, height: int, max_value: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as f:
        f.write(f"P5\n# generated by make_static_obstacle_map.py\n{width} {height}\n{max_value}\n".encode("ascii"))
        f.write(image)


def _load_trajectory(path: Path) -> list[tuple[float, float]]:
    rows: list[tuple[float, float]] = []
    with path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append((float(row["x"]), float(row["y"])))
    if len(rows) < 10:
        raise ValueError(f"Trajectory has too few points: {path}")
    return rows


def _cumulative_distance(points: list[tuple[float, float]]) -> list[float]:
    distances = [0.0]
    for previous, current in zip(points, points[1:]):
        distances.append(
            distances[-1] + math.hypot(current[0] - previous[0], current[1] - previous[1])
        )
    return distances


def _world_to_pixel(xy: tuple[float, float], origin: list[float], resolution: float, height: int) -> tuple[int, int]:
    col = int(round((xy[0] - float(origin[0])) / resolution))
    row_from_bottom = int(round((xy[1] - float(origin[1])) / resolution))
    return col, height - 1 - row_from_bottom


def _sample_obstacle_centers(
    trajectory: list[tuple[float, float]],
    obstacle_count: int,
    seed: int,
    min_spacing_m: float,
    start_exclusion_m: float,
) -> list[tuple[float, float]]:
    rng = random.Random(seed)
    s_values = _cumulative_distance(trajectory)
    lap_length = s_values[-1]
    lower = min(start_exclusion_m, 0.25 * lap_length)
    upper = max(lower + 1.0, lap_length - start_exclusion_m)
    candidates = [idx for idx, s_value in enumerate(s_values) if lower <= s_value <= upper]
    if len(candidates) < obstacle_count:
        raise ValueError("Not enough trajectory points outside the start exclusion zone")

    chosen: list[int] = []
    shuffled = list(candidates)
    rng.shuffle(shuffled)
    for idx in shuffled:
        if all(abs(s_values[idx] - s_values[prev]) >= min_spacing_m for prev in chosen):
            chosen.append(idx)
            if len(chosen) >= obstacle_count:
                break
    if len(chosen) < obstacle_count:
        raise ValueError(
            f"Could only place {len(chosen)} obstacles with min spacing {min_spacing_m:.2f}m"
        )
    chosen.sort(key=lambda idx: s_values[idx])
    return [trajectory[idx] for idx in chosen]


def _draw_square_obstacles(
    image: bytearray,
    width: int,
    height: int,
    centers: list[tuple[float, float]],
    origin: list[float],
    resolution: float,
    size_m: float,
    occupied_value: int,
) -> list[dict[str, float]]:
    half_pixels = int(math.ceil(0.5 * size_m / resolution))
    records: list[dict[str, float]] = []
    for index, center in enumerate(centers, start=1):
        col, row = _world_to_pixel(center, origin, resolution, height)
        r0 = max(0, row - half_pixels)
        r1 = min(height, row + half_pixels + 1)
        c0 = max(0, col - half_pixels)
        c1 = min(width, col + half_pixels + 1)
        for pixel_row in range(r0, r1):
            offset = pixel_row * width
            for pixel_col in range(c0, c1):
                image[offset + pixel_col] = occupied_value
        records.append(
            {
                "id": index,
                "x": center[0],
                "y": center[1],
                "size_m": float(size_m),
                "pixel_col": int(col),
                "pixel_row": int(row),
            }
        )
    return records


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-map-yaml", default="maps/my_map.yaml")
    parser.add_argument("--trajectory-csv", default="code/outputs/csv/global_trajectory.csv")
    parser.add_argument("--output-dir", default="maps/generated_static_obstacles")
    parser.add_argument("--name", default=None)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--obstacle-count", type=int, choices=[2, 3], default=3)
    parser.add_argument("--obstacle-size-m", type=float, default=0.5)
    parser.add_argument("--min-spacing-m", type=float, default=2.0)
    parser.add_argument("--start-exclusion-m", type=float, default=3.0)
    parser.add_argument("--occupied-value", type=int, default=0)
    return parser.parse_args()


def _parse_scalar(value: str):
    value = value.strip()
    if value.startswith("[") and value.endswith("]"):
        return [float(item.strip()) for item in value[1:-1].split(",")]
    try:
        if "." in value:
            return float(value)
        return int(value)
    except ValueError:
        return value.strip("'\"")


def _read_map_yaml(path: Path) -> tuple[dict, list[str]]:
    raw_lines = path.read_text(encoding="utf-8").splitlines()
    parsed = {}
    for line in raw_lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or ":" not in stripped:
            continue
        key, value = stripped.split(":", 1)
        parsed[key.strip()] = _parse_scalar(value)
    return parsed, raw_lines


def _write_map_yaml(path: Path, raw_lines: list[str], image_name: str) -> None:
    output_lines = []
    image_written = False
    for line in raw_lines:
        if line.strip().startswith("image:"):
            output_lines.append(f"image: {image_name}")
            image_written = True
        else:
            output_lines.append(line)
    if not image_written:
        output_lines.insert(0, f"image: {image_name}")
    path.write_text("\n".join(output_lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    base_yaml = Path(args.base_map_yaml).resolve()
    repo_root = base_yaml.parent.parent
    trajectory_csv = Path(args.trajectory_csv)
    if not trajectory_csv.is_absolute():
        trajectory_csv = repo_root / trajectory_csv

    map_info, raw_yaml_lines = _read_map_yaml(base_yaml)
    image_path = Path(map_info["image"])
    if not image_path.is_absolute():
        image_path = base_yaml.parent / image_path

    image, width, height, max_value = _read_pgm(image_path)
    trajectory = _load_trajectory(trajectory_csv)
    centers = _sample_obstacle_centers(
        trajectory,
        args.obstacle_count,
        args.seed,
        args.min_spacing_m,
        args.start_exclusion_m,
    )
    records = _draw_square_obstacles(
        image,
        width,
        height,
        centers,
        map_info["origin"],
        float(map_info["resolution"]),
        args.obstacle_size_m,
        int(args.occupied_value),
    )

    name = args.name or f"{base_yaml.stem}_obs{args.obstacle_count}_seed{args.seed}"
    output_dir = Path(args.output_dir)
    if not output_dir.is_absolute():
        output_dir = repo_root / output_dir
    pgm_path = output_dir / f"{name}.pgm"
    yaml_path = output_dir / f"{name}.yaml"
    manifest_path = output_dir / f"{name}.json"

    _write_pgm(pgm_path, image, width, height, max_value)
    _write_map_yaml(yaml_path, raw_yaml_lines, pgm_path.name)
    manifest_path.write_text(
        json.dumps(
            {
                "base_map_yaml": str(base_yaml),
                "trajectory_csv": str(trajectory_csv),
                "map_path": str(pgm_path.with_suffix("")),
                "map_yaml": str(yaml_path),
                "seed": args.seed,
                "obstacle_count": args.obstacle_count,
                "obstacles": records,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"map_path={pgm_path.with_suffix('')}")
    print(f"map_yaml={yaml_path}")
    print(f"manifest={manifest_path}")


if __name__ == "__main__":
    main()
